---
title       : StockVis
subtitle    : Visualization of Stock Market Data
author      : Srpi7947
job         : Jedi Knight
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Why do you need Stock market data

1. In finance, market data is price and trade-related data for a financial instrument reported by a trading venue such as a stock exchange. 

2. Market data allows traders and investors to know the latest price and see historical trends for instruments such as equities, fixed-income products, derivatives and currencies.

--- .class #id 

## Why is it important?

1. Whenever a company wants to raise funds for further expansion or settling up a new business venture, they have to either take a loan from a financial organization or they have to issue shares through the stock market. 

2. In fact the stock market is the primary source for any company to raise funds for business expansions. If a company wants to raise some capital for the business it can issue shares of the company that is basically part ownership of the company. 

3. To issue shares for the investors to invest in the stocks a company needs to get listed to a stocks exchange and through the primary market of the stock exchange they can issue the shares and get the funds for business requirements

--- &radio

## Visualize the stock for Facebook

What is the stock market code for Facebook?

1. Facebook

2. _FB_

3. FBook

4. Mark Zuckerberg

Once you have realized the actual symbol for Facebook, access Stockvis using the following link 

https://srpi7947.shinyapps.io/stockVis/

Enter the code for Facebook and click Submit

*** .hint
The symbol for Facebook is ideally its short form


---

## Be a stock market champion

### Use stockVis for all your stock market needs

1. Keep informed about all your company and trading stocks from your own webpage

2. Forget the complicated systems provided by major finance websites

3. StockVis is created for you keeping in mind a simple UI and a simplified output, showing you only what you need to know


